import type {
  DeepDiveContext,
  DeepDiveResponse,
  InsightInterpretation,
  StructuredForecastInput,
  StructuredInsightInput,
} from '../types';
import { BaseAnalyticsProvider } from './base';

export class MockAiProvider extends BaseAnalyticsProvider {
  readonly name = 'mock-ai-provider';

  async interpretInsights(facts: StructuredInsightInput[]): Promise<InsightInterpretation[]> {
    return facts.map((fact) => ({
      title: fact.title,
      message: fact.message,
      reason: 'This is a mock reason generated by the mock AI provider.',
      impact: 'This is a mock impact assessment.',
      recommendation: 'This is a mock recommendation based on the data.',
    }));
  }

  async interpretForecast(forecast: StructuredForecastInput): Promise<{ explanation: string }> {
    return {
      explanation: `Based on your recent spending patterns, we project a total spend of ${forecast.predictedAmount} for this period. ${forecast.confidenceExplanation || ''}`,
    };
  }

  async deepDive({ question }: DeepDiveContext): Promise<DeepDiveResponse> {
    return {
      answer: `This is a mock deep dive answer for: "${question}". In a real scenario, this would be generated by an AI model analyzing your specific expenses and spending patterns.`,
      suggestedFollowUps: [
        'How can I reduce this spending?',
        'What is the trend for this category over the last 6 months?',
        'Are there any unusual transactions here?',
      ],
    };
  }

  async recommendBudgets({
    categories,
  }: {
    categories: string[];
  }): Promise<Array<{ categoryId: string; recommendedAmount: number; explanation: string }>> {
    return categories.map((categoryId) => ({
      categoryId,
      recommendedAmount: 100,
      explanation: 'Mock recommendation based on past average spending.',
    }));
  }
}
