import type {
  DeepDiveContext,
  DeepDiveResponse,
  InsightInterpretation,
  StructuredForecastInput,
  StructuredInsightInput,
} from '../types';
import { BaseAnalyticsProvider } from './base';

export class MockAiProvider extends BaseAnalyticsProvider {
  readonly name = 'mock-ai-provider';

  async interpretInsights(facts: StructuredInsightInput[]): Promise<InsightInterpretation[]> {
    return facts.map((fact) => ({
      title: fact.title,
      message: fact.message,
      reason: 'This is a mock reason generated by the mock AI provider.',
      impact: 'This is a mock impact assessment.',
      recommendation: 'This is a mock recommendation based on the data.',
    }));
  }

  async interpretForecast(forecast: StructuredForecastInput): Promise<{ explanation: string }> {
    return {
      explanation: `Based on your recent spending patterns, we project a total spend of ${forecast.predictedAmount} for this period. ${forecast.confidenceExplanation || ''}`,
    };
  }

  async deepDive(context: DeepDiveContext): Promise<DeepDiveResponse> {
    return {
      answer: `This is a detailed mock explanation for the insight "${context.insight.title}". The data shows you spent ${context.insight.evidence?.currentSpend || 'an unknown amount'} in this category.`,
      suggestedFollowUps: [
        'How can I reduce this spending?',
        'Show me my transactions for this category',
      ],
    };
  }
}
